#!/bin/sh

echo "3DO Company, The - 3DO"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/3do_arcade_saot.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/goldstar.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz10.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz10e-anvil.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz10e-anvil-norsa.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz10ja-anvil-kanji.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz10-norsa.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz1.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz1j.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz1j-kanji.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz1j-norsa.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/panafz1-kanji.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/3DO%20Company%2C%20The%20-%203DO/sanyotry.bin"

echo "Amstrad - CPC"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Amstrad - CPC/cpc464.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Amstrad - CPC/cpc6128.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Amstrad - CPC/cpc664.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Amstrad - CPC/cpc_amsdos.rom"

echo "Arcade"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/bubsys.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/cchip.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/decocass.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/isgsm.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/midssio.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/neogeo.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/nmk004.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/pgm.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/skns.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Arcade/ym2608.zip"

echo "Atari - 400-800"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - 400-800/ATARIBAS.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - 400-800/ATARIOSA.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - 400-800/ATARIOSB.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - 400-800/ATARIXL.ROM"

echo "Atari - 5200"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - 5200/5200.rom"

echo "Atari - 7800"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - 7800/7800 BIOS (E).rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - 7800/7800 BIOS (U).rom"

echo "Atari - Lynx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - Lynx/lynxboot.img"

echo "Atari - ST"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Atari - ST/tos.img"

echo "Coleco - ColecoVision"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Coleco - ColecoVision/colecovision.rom"

echo "Commodore - Amiga"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Commodore - Amiga/kick34005.A500"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Commodore - Amiga/kick40063.A600"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Commodore - Amiga/kick40068.A1200"

echo "Enterprise - 64-128"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/basic20.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/basic21.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/brd.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/epd19hft.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/epfileio.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/exdos13.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/exos20.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/exos21.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/exos24uk.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/hun.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/zt18hfnt.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Enterprise - 64-128/zt19uk.rom"

echo "Fairchild Channel F"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Fairchild Channel F/sl31253.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Fairchild Channel F/sl31254.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Fairchild Channel F/sl90025.bin"

echo "Id Software - Doom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Id Software - Doom/prboom.wad"

echo "J2ME"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/J2ME/freej2me.jar"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/J2ME/freej2me-lr.jar"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/J2ME/freej2me-sdl.jar"

echo "MacII"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/MacII/MacII.ROM"

echo "Magnavox - Odyssey2"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Magnavox - Odyssey2/o2rom.bin"

echo "Mattel - Intellivision"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Mattel - Intellivision/exec.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Mattel - Intellivision/grom.bin"

echo "Microsoft - MSX"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/CARTS.SHA"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/CYRILLIC.FNT"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/DISK.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/FMPAC16.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/FMPAC.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/ITALIC.FNT"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/KANJI.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/MSX2EXT.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/MSX2PEXT.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/MSX2P.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/MSX2.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/MSXDOS2.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/MSX.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/PAINTER.ROM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Microsoft - MSX/RS232.ROM"

echo "NEC - PC-98"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/2608_bd.wav"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/2608_hh.wav"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/2608_rim.wav"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/2608_sd.wav"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/2608_tom.wav"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/2608_top.wav"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/bios.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/font.bmp"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/font.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/itf.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-98/sound.rom"

echo "NEC - PC Engine - TurboGrafx 16 - SuperGrafx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC Engine - TurboGrafx 16 - SuperGrafx/gecard.pce"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC Engine - TurboGrafx 16 - SuperGrafx/gexpress.pce"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC Engine - TurboGrafx 16 - SuperGrafx/syscard1.pce"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC Engine - TurboGrafx 16 - SuperGrafx/syscard2.pce"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC Engine - TurboGrafx 16 - SuperGrafx/syscard2u.pce"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC Engine - TurboGrafx 16 - SuperGrafx/syscard3.pce"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC Engine - TurboGrafx 16 - SuperGrafx/syscard3u.pce"

echo "NEC - PC-FX"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-FX/fx-scsi.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-FX/pcfxbios.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-FX/pcfxga.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-FX/pcfx.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/NEC - PC-FX/pcfxv101.bin"

echo "Nintendo - Famicom Disk System"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Famicom Disk System/disksys.rom"

echo "Nintendo - Gameboy"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Gameboy/dmg_boot.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Gameboy/gb_bios.bin"

echo "Nintendo - Game Boy Advance"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Game Boy Advance/gba_bios.bin"

echo "Nintendo - Gameboy Color"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Gameboy Color/cgb_boot.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Gameboy Color/gbc_bios.bin"

echo "Nintendo - GameCube"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-dvd-20010608.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-dvd-20010831.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-dvd-20020402.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-dvd-20020823.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-ntsc-10.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-ntsc-11.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-ntsc-12.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-pal-10.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-pal-11.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - GameCube/gc-pal-12.bin"

echo "Nintendo - Nintendo 64DD"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Nintendo 64DD/64DD_IPL.bin"

echo "Nintendo - Nintendo DS"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Nintendo DS/bios7.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Nintendo DS/bios9.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Nintendo DS/firmware.bin"

echo "Nintendo - Nintendo Entertainment System"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Nintendo Entertainment System/NstDatabase.xml"

echo "Nintendo - Pokemon Mini"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Pokemon Mini/bios.min"

echo "Nintendo - Satellaview"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Satellaview/BS-X.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Satellaview/BS-X (En).bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Satellaview/BS-X (En) (DRM-Free).bin"

echo "Nintendo - SuFami Turbo"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - SuFami Turbo/STBIOS.bin"

echo "Nintendo - Super Game Boy"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Game Boy/sgb1.boot.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Game Boy/sgb1.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Game Boy/SGB1.sfc"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Game Boy/sgb2_bios.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Game Boy/sgb2.boot.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Game Boy/sgb2.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Game Boy/SGB2.sfc"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Game Boy/sgb_bios.bin"

echo "Nintendo - Super Nintendo Entertainment System"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/cx4.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp1b.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp1b.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp1.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp1.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp2.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp2.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp3.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp3.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp4.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/dsp4.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/st010.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/st010.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/st011.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/st011.program.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/st018.data.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Nintendo - Super Nintendo Entertainment System/st018.program.rom"

echo "Phillips - Videopac+"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Phillips - Videopac+/c52.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Phillips - Videopac+/g7400.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Phillips - Videopac+/jopac.bin"

echo "ScummVM"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/ScummVM/scummvm.zip"

echo "Sega - Dreamcast/dc"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast/dc/boot.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast/dc/dc_boot.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast/dc/flash.bin"

echo "Sega - Dreamcast-based Arcade/dc"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast-based Arcade/dc/airlbios.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast-based Arcade/dc/awbios.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast-based Arcade/dc/f355bios.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast-based Arcade/dc/f355dlx.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast-based Arcade/dc/hod2bios.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast-based Arcade/dc/naomi2.zip"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Dreamcast-based Arcade/dc/naomi.zip"

echo "Sega - Game Gear"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Game Gear/bios.gg"

echo "Sega - Master System - Mark III"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Master System - Mark III/bios_E.sms"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Master System - Mark III/bios_J.sms"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Master System - Mark III/bios.sms"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Master System - Mark III/bios_U.sms"

echo "Sega - Mega CD - Sega CD"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega CD - Sega CD/bios_CD_E.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega CD - Sega CD/bios_CD_J.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega CD - Sega CD/bios_CD_U.bin"

echo "Sega - Mega Drive - Genesis"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega Drive - Genesis/areplay.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega Drive - Genesis/bios_MD.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega Drive - Genesis/ggenie.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega Drive - Genesis/rom.db"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega Drive - Genesis/sk2chip.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Mega Drive - Genesis/sk.bin"

echo "Sega - Saturn"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/hisaturn.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/mpr-17933.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/mpr-18100.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/mpr-18811-mx.ic1"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/mpr-19367-mx.ic1"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/saturn_bios.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/sega1003.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/sega_100a.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/sega_100.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/sega_101.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sega - Saturn/vsaturn.bin"

echo "Sharp - X1"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sharp - X1/iplrom.x1"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sharp - X1/iplrom.x1t"

echo "Sharp - X68000"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sharp - X68000/cgrom.dat"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sharp - X68000/iplrom30.dat"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sharp - X68000/iplromco.dat"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sharp - X68000/iplrom.dat"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sharp - X68000/iplromxv.dat"

echo "Sinclair - ZX Spectrum"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/128-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/128-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/128p-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/128p-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/128-spanish-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/128-spanish-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/256s-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/256s-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/256s-2.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/256s-3.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/48.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/disciple.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/disk_plus3.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/gluck.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/if1-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/if1-2.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus2-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus2-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus3-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus3-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus3-2.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus3-3.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus3e-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus3e-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus3e-2.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plus3e-3.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/plusd.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/se-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/se-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/speccyboot-1.4.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_128.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_16.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_2048.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_2068.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_48.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_pentagon.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_plus2a.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_plus2.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_plus3e.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_plus3.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_scorpion.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_se.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tape_ts2068.szx"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tc2048.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tc2068-0.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/tc2068-1.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/trdos.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/zx128.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sinclair - ZX Spectrum/zx48.rom"

echo "SNK - NeoGeo CD"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/000-lo.lo"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/front-sp1.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/neocd.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/neocd_f.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/neocd_sf.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/neocd_st.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/neocd_sz.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/neocd_t.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/neocd_z.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/top-sp1.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/SNK - NeoGeo CD/uni-bioscd.rom"

echo "Sony - PlayStation"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph1000.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph1001.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph1002.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph100.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph101.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph102A.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph102B.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph102C.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph3000.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph3500.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph5000.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph5500.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph5501.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph5502.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph5552.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph7001.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph7002.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph7003.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph7502.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation/scph9002(7502).bin"

echo "Sony - PlayStation 2/pcsx2/bios"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0100j-20000117.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0100jd-20000117.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0101j-20000217.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0101jd-20000217.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0101xd-20000224.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0110a-20000727.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0110ad-20000727.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0120a-20000902.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0120e-20000902.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0120ed-20000902-20030110.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0120ed-20000902.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0120j-20001027-185015.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0120j-20001027-191435.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0150a-20001228.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0150ad-20001228-20030520.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0150e-20001228.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0150ed-20001228-20030520.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0150j-20010118.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0150jd-20010118.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160a-20010427.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160a-20010704.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160a-20011004.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160a-20020207.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160e-20010704.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160e-20011004.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160e-20020319.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160e-20020426.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160h-20010730.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160h-20020426.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160j-20010427.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0160j-20020426.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0170a-20030325.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0170ad-20030325.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0170e-20030227.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0170ed-20030227.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0170j-20030206.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0180cd-20030224.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0180j-20031028.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190a-20030623.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190a-20040329.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190c-20030623.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190e-20030623.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190e-20030822.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190h-20030623.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190j-20030623.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190j-20030822.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0190r-20030623.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0200a-20040614.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0200e-20040614.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0200ed-20040614.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0200h-20040614.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0200j-20040614.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0210j-20040917.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220a-20050620.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220a-20060210.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220a-20060905.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220ad-20050620.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220ad-20060905.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220e-20050620.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220e-20060210.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220e-20060905.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220h-20050620.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220h-20060210.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220h-20060905.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220j-20050620.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220j-20060210.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0220j-20060905.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0230a-20080220.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0230e-20080220.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0230h-20080220.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0230j-20080220.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0250e-20100415.bin"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation 2/pcsx2/bios/ps2-0250j-20100415.bin"

echo "Sony - PlayStation Portable"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Sony - PlayStation Portable/ppge_atlas.zim"

echo "Videoton - TV Computer"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Videoton%20-%20TV%20Computer/tvc22_ext.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Videoton%20-%20TV%20Computer/tvc22_sys.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Videoton%20-%20TV%20Computer/tvc_dos12d.rom"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Videoton%20-%20TV%20Computer/tvcfileio.rom"

echo "Wolfenstein 3D"
wget -c "https://github.com/Luciano2018/LakkaBios/raw/main/System/Wolfenstein%203D/ecwolf.pk3"
